### PR TITLE
feat: add `deno` entry

### LINKED ISSUE #3: Feature request: Compatibility with Deno
Hey @lukeed, I find myself revisiting this module, because I'm part way towards [adding ESM support to yargs](https://github.com/yargs/yargs/issues/1706).

**I have a feature request ...**

Would you be open to using dependency injection in this library, similar to what I've done in [yargs-parser](https://github.com/yargs/yargs-parser/blob/master/deno.ts), to target Deno as well?

The main advantage I see to this is that it helps isolate the Node-specific APIs you're using, making it easier to target a variety of other platforms.

### PR DESCRIPTION
**Pull request by lukeed**
First pass at a Deno entry. 
All `fs.*` operations are available under `Deno` namespace.
Only had to import `std:path` module.

**Questions:**

1) Both `Deno.*` operations require the `allow-read` permission. Is this something I have to flag on my side?
2) Is there a better/built-in way to go from AyncIterator to Array?
3) Do I have to add `/deno` to my package.json files? Assume not since publishing works thru git releases only

//cc @bcoe

---

Closes #3

### CODE REVIEW

**Comment by bcoe** [comment]
> Both Deno.* operations require the allow-read permission. Is this something I have to flag on my side?

I've been capturing the error, and providing a useful note for users. It sounds like there is a way to prompt for permissions, might be a good option too:

https://dev.to/bmorearty/better-deno-security-ask-for-permission-at-runtime-1fnm

> Is there a better/built-in way to go from AyncIterator to Array?

I'm not sure. Your approach seemed pretty reasonable to me 👍 

> Do I have to add /deno to my package.json files? Assume not since publishing works thru git releases only

No, you should be able to ignore `/deno`.

**Review by bcoe — COMMENTED** [review]
This is looking good 👍 for `yargs`, I will need the [`sync` option](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.readDirSync)

I think, I'd be happy to pitch in if you run out of cycles this week.

**Comment by lukeed** [comment]
Thanks! I'll add extra sync entry. I figured everything would be async in Deno because of top-level await but obviously that was a bad assumption.

I think permissions is all that's left to solve. Catching it makes sense for a `yargs` but I don't think it would for every module down the tree.

Happy to focus on it this week. Would hate to be the blocker for your conversion effort

**Comment by bcoe** [comment]
@lukeed yes, let me know where you land on permissions, this  is something I'm trying  to learn to navigate too.

**Comment by lukeed** [comment]
Hey, so I [asked the Deno Discord](https://discord.com/channels/684898665143206084/684898665151594506/742585193008857099) and the recommendation is to allow the permission errors to happen. Any required permissions should be listed in the README (or in the functions' jsdoc blocks), and it's ultimately up to the consumer to add the appropriate flags. This is also how you can get method/usage-driven granular permissions.

I found feature proposals in the Deno repo about adding manifests/import-map-like files to define the permissions ahead of time, but there's not been any action taken on them yet. Design still WIP

**Pull request merged**
